services:
  - type: web
    name: karteikarten-app
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/karteikarten-app-0.0.1-SNAPSHOT.jar
    plan: free
    branch: main